### ISSUE TITLE
adb/fastboot/mtp do not work

### ISSUE THREAD

**Issue by light4** [iusmac/recovery_rova#5]
All USB related function don't work when boot to this recovery.
Works fine when boot to android or fastboot.

device: xiaomi-riva
recovery version: OrangeFox-R11.1_5, OrangeFox-R11.1_3

**Comment by iusmac** [comment]
> All USB related function don't work when boot to this recovery.

Of course everything is working fine on all my PCs (1 desktop, 2 laptops) on Ubuntu/Win10/Win11. Check your drivers.

**Comment by light4** [comment]
Is your device `xiaomi-riva`? The usb device seems like not even charged. `lsusb` shows nothing.

**Comment by iusmac** [comment]
Mine is rolex. But we have a Telegram group for rova devices and everything works fine, nobody complained about USB issues. All works just right the way.

**Comment by light4** [comment]
Turns out I flashed latest stock rom, which firmware is not working with this recovery.
Flashed back `riva_images_V10.1.1.0.NCKCNFI_20181019.0000.00_7.1_cn/`,  recovery works perfect.
Thanks a lot.
