### ISSUE TITLE
redmi 5a(riva) can't install lineage 20

### ISSUE THREAD

**Issue by redomCL** [iusmac/recovery_rova#6]
redmi 5a(riva) can't install lineage 20 use [OrangeFox-R11.1_5](https://github.com/iusmac/recovery_rova/releases/tag/R11.1_5).
log show:"failed mount /system".

**Comment by iusmac** [comment]
Use [OrangeFox-R11.1_6](https://github.com/iusmac/recovery_rova/releases/tag/R11.1_6) to install RDP ROMs.
